### ISSUE TITLE
Script always load from block 462000

### ISSUE THREAD

**Issue by ghost** [jansenmarc/WavesLPoSDistributer#1]
Hi recently started a node at height about 800000. While testing the script, i noticed that it was trying to load blocks from block 462000 hence running out of memory.

This is due to line 94 in app.js:
    
    // leases have been resetted in block 462000, therefore, this is the first relevant block to be considered
    var firstBlockWithLeases = 462000;

Proposal of moving this parameter in the config section with a selfexplainingname like for example: _firstBlockNodeActive_

**Comment by jansenmarc** [comment]
This is not a bug. The problem is that leases potentially start at block 462000.

**Comment by ghost** [comment]
Hi :), sorry i didn't meant to open a bug but more a suggestion (and thank you for your script). 

Like a parameter where a owner node can configure a block from where to start avoiding touching function getAllBlocks(). 

Even if leases started from block 462000 a nodeowner that has activated the node in say, block 800000 doesn't need (i think) to load blocks from 462000 because their lease will be after block 800000.

**Comment by jansenmarc** [comment]
Yes, i understand what you mean, and i agree to some extend. Nevertheless, i would like to keep the config section for settings that really NEED to configured. The 462000 does not need to be configured (but could be, if you know what you do). Therefore, i would not like to add it to the config section. Still, if you know what you do, you can change it in your local clone...

**Comment by marsappslab** [comment]
Hello,

Thank you for the script!

I need for manage Airdrop transaction with more then 100 wallets.

Any Quick Starter Documentation (setups, wallet list file format, node adresse definition? How to calculate the fees? ) 

Kind regards.

**Comment by jansenmarc** [comment]
Hi,

you would need your own script that creates the payment file. The format could be found in the airdrop.js or the appFastNG.js file. The node is configured in the config section and the fees should be standard fees.

Cheers
  Marc

**Comment by marsappslab** [comment]
Hi,

Thank you for all the information! One thing I'm not sure about. In the Airdrop.js the difference between:
- assetId: id of the reference asset (Waves Id ?)
- assetToDistributeId: id of the asset you want to airdrop (The token build upon Waves ?)

Kind regards.
